🎨 Buttons models implamentation
ThundeRatz/Monitracer pull request #16
Opened 2021-11-01 22:08 UTC by DamaralHenrique

![image](https://user-images.githubusercontent.com/62445591/139747973-11d17b58-caac-4b97-9427-1655b13ee544.png)

Nesta PR temos a implementação dos diferentes tipos de botao utilizados: 
- Botão princpal
- Botão Principal pequeno
- Botão secundário
- Botão terciário
- Botão de ação
- Botão de ação vermelho
- Botão do regulamento (Não apresentado na figura)

Além disso, a Home page foi alterada para receber o teste dos novos botões (Alteração descartável) e a colors foi consertada para ajustar as cores lightThunderBlue e lightThunderYellow.

2021-11-02 04:14 UTC, guedeslucas1 submitted a review, later dismissed
botões bonitos, gostei. Só uma coisa, antes de dar o merge a gente vai dar pull das mudanças que ja tão na develop (header e etc)?

2021-11-02 04:14 UTC, guedeslucas1 commented on src/components/button.js
> +    marginBottom: -20 - 2 * SPACING.small,
medo de isso não se adaptar bem a outras telas. Mas acho que a gente não precisa ver isso agora, só comentando.

2021-11-08 09:04 UTC, VanderSant requested changes
Não tive o prazer de testar direto no meu celular, mas assim que der tempo eu posso comentar mais alguma coisa. No geral eu gostei do botões, sei como foi difícil tornar esses botões viáveis, então bom trabalho, gente!

2021-11-08 09:04 UTC, VanderSant commented on src/HomePage.js
> +      </Header> */}
Por que deixaram isso comentado? Se não forem usar mais eu acho melhor excluir de vez

2021-11-08 09:04 UTC, VanderSant commented on src/components/button.js
> + * @date 10/2021
tem que atualizar a data

2021-11-08 09:04 UTC, VanderSant commented on src/components/button.js
> +      <TouchableOpacity onPress={props.onPress} style={[{ transform: [{ rotate: "-14deg" }] }]}>
Esse 
```js
 {[{ transform: [{ rotate: "-14deg" }] }]}
``` 
está sendo repetido várias vezes. Não daria para criar uma StyleSheet ou algo do tipo para facilitar mudar depois caso precise?

2021-12-03 20:41 UTC, DamaralHenrique commented on src/components/button.js
> +    marginBottom: -20 - 2 * SPACING.small,
Bom, eu tbm n sei os impactos disso em outros tamanho de tela, mas vamos manter assim por enquanto pq ta funcionando. Mas acho q isso pode ser facilmente revisto e consertado depois, caso haja problema

2021-12-04 17:43 UTC, VanderSant approved these changes
acho que está top, mandaram muito galera!

2022-01-17 23:34 UTC, GabrielKishida commented on src/components/button.js
> +    marginBottom: -20 - 2 * SPACING.small,
Então, o maior problema desses "números mágicos" é esse mesmo de ser meio esquisito adaptá-lo para outras telas. Acho que vale a gente repensar em corrigir isso aqui ou trabalhar com botões horizontais ao invés de inclinados.

Isso é um questionamento que eu gostaria de ter com vocês ao vivo também -- quando um botão é inclinado, o que determina o tamanho (horizontal e vertical) que ele vai ocupar? O texto dentro dele? O espaço que ele pode ocupar?

O maior problema do diagonal é que são duas variáveis a se considerar: ao se expandir na horizontal ele também ganha tamanho vertical. Quando o botão é simplesmente horizontal não temos essa preocupação.

Acho que em termos de desenvolvimento o mais simples é determinar que o botão não tenha quebra de linhas, ou no máximo um número suportável de quebra de linhas para o texto dentro dele. Se a gente deixar flexível ele sempre será problemático de um jeito ou de outro.

2022-01-17 23:35 UTC, GabrielKishida commented on src/components/button.js
> +    marginBottom: -20 - 2 * SPACING.small,
Esse trampo todo me fez questionar se vale mais a pena fazer botões horizontais ao invés de quebrar tanto a cabeça, mas não curto a ideia de desistir do nosso design original

2022-01-17 23:35 UTC, GabrielKishida approved these changes
Como eu fui co autor disso tudo, acho que tenho que dar approve moral

No entanto acho que vale rever o comentário do Guedes e o que eu coloquei embaixo, para repensar a viabilidade do botão diagonal.

2022-01-18 00:15 UTC, merged