🔀 Feature/server communication
ThundeRatz/Monitracer pull request #8
Opened 2021-09-18 02:39 UTC by VanderSant

Olá, gente

Nessa pr, que visava implementar a base da comunicação  com o servidor e criar uma paǵina de testes para isso, foi adicionado os seguintes arquivos:

Na pasta "server_communication" :
- api_config.js
- constants_api.js
- data_receiver.js
- data_sender.js
- laps_api.js

Na pasta "tests":
- TestServerPage

<p align="center">
<img src="https://user-images.githubusercontent.com/76136276/133869174-c20f4f53-8ea3-4d29-b0d6-fd2933c670ca.jpeg" alt="alt text" width="300"/>
</p>

2021-09-21 05:20 UTC, d-nery requested changes
Hello, alguns vários comentários com o mais variado grau de importância, dessa vez eu li com mais calma então tem muito mais comentário.

Só lembrando que algumas coisas não necessariamente precisam ser mudadas/implementadas agora, já que é uma versão bem inicial, é só pra terem uma ideia

Algumas coisas gerais:
- Eu vi que tem um `.flowconfig` na raiz do projeto, mas não vi usando tipagem em lugar nenhum, seria bom por, facilita a vida
- Eu vi também que tem um `.eslintrc.js` na raiz, com as configs do eslint, estão rodando? Pq rodei aqui e ele achou 8 erros e 104 warnings 😬, inclusive muito provável que várias das coisas que eu comentei apareçam aí
- Outro grande problema é que você tem um `package-lock.json` e um `yarn.lock`, o que quer dizer que estão rodando o yarn e o npm, e isso não pode, eles brigam, escolham um (recomendo deixar só o yarn)

2021-09-21 05:20 UTC, d-nery commented on src/components/BTList.js
> +  const [BTInit, BTRemove, EnableBT, DisableBT, BTLogin, lista, bolEnableBlu] =
A única função que você usa aqui é a `BTLogin`, não precisa declarar todas as outras, você pode fazer assim ~~eu sei que é feio~~: `const [, , , , BTLogin] = BTConnection();`, ou até um simples `const BTLogin = BTConnection()[4];` (mas aí melhor o primeiro pra não ficar pegando índice)

2021-09-21 05:20 UTC, d-nery commented on src/components/BTList.js
> +  const [BTInit, BTRemove, EnableBT, DisableBT, BTLogin, lista, bolEnableBlu] =
E falando do resto do arquivo, tem váários imports não usados, é melhor tirar (em vários outros arquivos também, o ESLint avisa, o VS Code pinta)

2021-09-21 05:20 UTC, d-nery commented on src/components/button.js
> +          PostLap(
`PostLap` é async, creio que deva ser 

```js
onPress={async () => await PostLap(...)}
```

2021-09-21 05:20 UTC, d-nery commented on src/components/button.js
> +        onPress={() => GetConstantsList(props)}
O mesmo sobre o async vale aqui

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/api_config.js
> +export const api = 'https://api.thunderatz.org/tracer';
Seria bom esse tipo de coisa ficar num arquivo mais genérico com todas as configs, mas por hora acho que tá bom assim mesmo

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/constants_api.js
> +      1: parseFloat(kp),
Lembrando que esses valores são aquele mapeamento de `id -> tipo de contante`, então não fica claro assim o que quer dizer um "1", seria bom concentrar isso em algum lugar, ter um arquivo de tipos de constantes com algo do tipo

```js
export const constant_types {
    KP: 1,
    KI: 2,
    KD: 3,
};
```

E aí quando precisar usar só fazer `constant_types.KI` (não necessariamente com esses nomes, só um exemplo)


Além disso, aqui ainda tá bem fixo em KP, KI, KD, aí já é bom ter na cabeça o que vão fazer quando for implementar algo mais genérico, que envie qualquer tipo de contante

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/constants_api.js
> +  await PostData('constants', data);
Seria bom ter todos esses nomes dos endpoints em um enum que nem disse ali pros tipos de contants, pra poder fazer um `endpoints.CONSTANTS` ou algo assim

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/constants_api.js
> +  for (var i in constants_list) {
Tá, várias coisas aqui.

Isso foi testado? `for...in` não funciona desse jeito em javascript, ele itera meio arbitrariamente sobre as propriedades, inclusive algumas que você pode não ver. No fim vai acabar funcionando, mas por trás não tá acontecendo o que você queria e ele itera muito mais, pra fazer desse jeito seria com `for...of`, que já pega o elemento direto e funciona basicamente como em python:

```js
for (const constant of constants_list) {
    if (constant.name === constant_name) {
        return constant.values;
    }
}
```

Aí nesse exemplo já mostrei algumas outras coisas: 
1. Sempre que possível coloque `const`, e, caso não seja pra ser uma constante, use `let`, `var` não deve ser usado em praticamente nenhum contexto, ele funciona esquisito e é mais antigo.
2. Sempre melhor acessar propriedades com o `.` em vez do `[]`
3. Lembrem de usar `===` em vez de `==`

----

Dito isso, existem muitos métodos de lidar com arrays e tudo isso poderia ser simplesmente:

```js
const constants_list = await GetConstantsList();
return constants_list.find(c => c.name === constant_name)?.values ?? [];
```

(Usei uns coalesces aí pra não retornar undefined e sim uma lista vazia se não encontrar)

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/constants_api.js
> +  for (var i in constant_list) {
Quase a mesma coisa do caso de cima, mas nesse caso faz sentido retornar null (não undefined, retorne null)

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/constants_api.js
> +  for (var i in constant_list) {
Idem ao resto, só reiterando pra jamais retornar `undefined` propositalmente, quando você não quer que tenha valor, retorne `null`

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/data_receiver.js
> +    return true;
Não dá pra chegar aqui hehe

Aí no caso acho que ali embaixo é melhor retornar null (fora do catch inclusive, já que tem esse retorno dentro do try), não faz sentido retornar um objeto ou false, tem que ser ou bool (true/false) ou um objeto (que pode ser null), nunca misture dois tipos de retorno

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/data_sender.js
> +    return true;
Mesma coisa do que comentei no no Get, aqui tudo bem ser true/false se você não vai usar o retorno. Mas se não me engano, depois que você faz um POST a API te retorna o objeto completo, com ID e tudo mais, então mesmo que você não use fora, creio que como função, faz sentido ela retornar o que volta da API (ou null se der erro, como dito lá no outro comentário)

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/laps_api.js
> +  for (var i in laps_list) {
Aqui e na debaixo idem ao que comentei nas outras lá das constantes

2021-09-21 05:20 UTC, d-nery commented on src/server_communication/package.json
> +{
Pq esse arquivo existe 🧐

2021-09-21 05:20 UTC, d-nery commented on src/tests/TestServerPage.js
> +  const [inputname, setInputname] = React.useState('');
`input_name`? (serve pras próximas linhas)

2021-09-21 05:20 UTC, d-nery commented on src/BluetoothListPage.js
> +  const [BTInit, BTRemove, EnableBT, DisableBT, BTLogin, lista, bolEnableBlu] =
Lembrando que todas essas funções aqui são async e não tem nenhum await nelas daqui pra baixo hehe

~~achei engraçado que o outro arquivo usa só a BTLogin e esse usa tudo menos essa~~

2021-09-21 05:20 UTC, d-nery commented on android/app/src/main/AndroidManifest.xml
>    package="com.monitracer">
Deveria ser `org.thunderatz.monitracer` (cuidado quando mudar isso pq tem que mexer em vários outros lugares)

2021-09-21 05:20 UTC, d-nery commented on android/app/src/main/AndroidManifest.xml
> +    <!--uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /-->
Pq adicionou isso comentado? asuhsauhusa

2021-10-02 08:56 UTC, VanderSant commented on android/app/src/main/AndroidManifest.xml
> +    <!--uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /-->
ah, quando eu estava com problemas em usar a API, eu pesquisei se não poderia ser problema no app, ai eu vi uma série de medidas que poderiam resolver esse problema esse problema de requisição/internet no geral. Deixei comentado pq achei que poderia ser útil um dia, como o app vai ter que funcionar em locais com redes diferentes. Não tenho tanta certeza se vai ser útil. Acha melhor tirar?

2021-10-02 16:38 UTC, d-nery commented on android/app/src/main/AndroidManifest.xml
> +    <!--uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /-->
Nunca se deixa código comentado assim, se for útil um dia alguém adiciona hehe

2021-10-19 18:13 UTC, d-nery approved these changes
Parece bom, acho que já podem juntar como está e novas coisas colocarem em novas branches :)

2021-10-19 18:13 UTC, d-nery commented on src/server_communication/constants_api.js
> +  for (let i = 0; i < constant_values.length; i++) {
De novo, não tá errado, mas geralmente com arrays tem jeitos mais prontos de se fazer essas transformações, isso poderia ser

```js
const value = constant_values.reduce((c, v, i) => ({...c, [i+1]: parseFloat(v) }), {})
```

2021-10-29 19:16 UTC, d-nery commented on src/server_communication/constants_api.js
> +    (acum, valor, i) => ({...acum, [i + 1]: parseFloat(valor)}),
`acum` 🤨

2021-10-29 19:37 UTC, GabrielKishida reviewed
Okay, nao foi tao ruim quanto eu pensei. Tem muitos arquivos aqui que sao de setup entao foi tranquilo revisar (desculpa fazer chororô no grupo, eu sou preguiçosah)

Comentei algumas coisas que eu acho importante dar uma olhada para nao dar problema no futuro.

Sobre o DataSenderButton estar no Button, eu acho que é uma definicao de arquitetura importante da gente pensar. Para mim, nao faz sentido uma instância do PrimaryButton estar junto com a definiçao do mesmo -- acho importante separar a funcionalidade do componente visual, sabe? Por exemplo, acredito que esse callback de enviar data pode estar em outros lugares, e nao precisa estar vinculado a um botao primário. Talvez a melhor saida seja fazer fazer um hook que nem você fez com o BTConnection() -- mas essa é só minha opiniao.

De qualquer forma, é bom ter esses callbacks separadinhos para caso a gente tenha que chamá-los em diferentes situacoes.

No mais, acho que só ver direitinho como fica o tratamento de erros. Reclamei de devolver [] ao invés de undefined pq eu acho que se você colocar `!![]` ele devolve true e `!!undefined` devolve false -- mas precisaria confirmar.

2021-10-29 19:37 UTC, GabrielKishida commented on package.json
> +    "react-native-navigation": "^7.21.0"
Eventualmente é legal a gente fixar essas versoes de packages (tirando o ^) pra caso um atualize sem que a gente perceba, o app nao quebre todo

2021-10-29 19:37 UTC, GabrielKishida commented on package.json
> +    "react-native-navigation": "^7.21.0"
Nao sei se faria nessa PR pq pode dar mt conflito mas algo para se pensar para um futuro proximo

2021-10-29 19:37 UTC, GabrielKishida commented on src/BluetoothListPage.js
> +          onValueChange={async () => await toggleBluetooth()}
precisa desse outro async await? Nao da pra deixar só toggleBluetooth?

2021-10-29 19:37 UTC, GabrielKishida commented on src/components/BTList.js
> +  const [, , , , BTLogin] = BTConnection();
Acho que já comentei isso, mas se você transformar esse BTConnection em objeto (usando chaves {}) ao invés de vetor (usando colchetes []) você nao precisaria fazer essa gambiarra de importar um monte de coisa antes pra conseguir o que você quer. Você poderia fazer só `{BTLogin} = BTConnection();` e ele pegaria pelo nome (mas aí teria que mudar no export do BTConnection)

2021-10-29 19:37 UTC, GabrielKishida commented on src/components/BTList.js
> +    ></FlatList>
:eyes: 
```suggestion
    />
```

2021-10-29 19:37 UTC, GabrielKishida commented on src/components/button.js
> +};
Nao sei se faz mt sentido isso aqui estar aqui. Ao meu ver, isso é só um PrimaryButton com a props onPress diferente. Faria mais sentido colocar esse callback assíncrono na tela onde ele é chamado.

2021-10-29 19:37 UTC, GabrielKishida commented on src/components/button.js
> +};
Mesma coisa que o DataSenderButton: é só um PrimaryButton com um callback específico. Dá pra deixar só o PrimaryButton e na página que é chamada colocar esse callback específico.

2021-10-29 19:37 UTC, GabrielKishida commented on src/server_communication/constants_api.js
> +  console.log('Id não encontrado - GetConstantsId\n');
Reflexao pro futuro: seria legal ter uma forma de apresentar erro para o usuário do aplicativo (seja com um modal ou alguma coisa assim), pq aqui seria invisivel no app, né

2021-10-29 19:37 UTC, GabrielKishida commented on src/server_communication/laps_api.js
> +  return [];
Meio ignorável, mas no comentário tá escrito que devolve undefined mas aqui devolve um vetor vazio. Isso pode ser perigoso pq eu acho que o javascript considera [] diferente de undefined, e acho até que vetores vazios nao sao falsy, entao tem que tomar cuidado só

2021-10-29 19:37 UTC, GabrielKishida commented on src/server_communication/laps_api.js
> +  return [];
Vi que vocês devolvem em outros lugares também um vetor [] como undefined. Nao sei se isso vai dar problema no futuro mas vale o pensamento

2021-10-29 19:42 UTC, d-nery commented on src/server_communication/constants_api.js
> +  console.log('Id não encontrado - GetConstantsId\n');
Pra essas coisas vocês querem [toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts)

2021-10-29 19:46 UTC, d-nery commented on src/server_communication/laps_api.js
> +  return [];
Acho que aqui foi só erro de não atualizar o comentário
Ser você ler a minha review lá do começo falo sobre retornar undefined em algum lugar dela

2021-10-29 19:49 UTC, DamaralHenrique approved these changes
Nice, parece tudo certinho! O @GabrielKishida já indicou todos os probleminhas basicamente kkkk e o meu comentário é batata só

2021-10-29 19:49 UTC, DamaralHenrique commented on src/tests/TestServerPage.js
> + * @file TestServer.js
```suggestion
 * @file TestServerPage.js
```

2021-10-29 19:51 UTC, VanderSant commented on package.json
> +    "react-native-navigation": "^7.21.0"
ah, justo, lembro que ele atualizou sozinho em um momento. pretendo abrir uma pr depois só para resolver problemas desse tipo, como o fato de ter yarn e package-lock.json no mesmo repositório.

2021-10-29 19:55 UTC, VanderSant commented on src/components/BTList.js
> +  const [, , , , BTLogin] = BTConnection();
acho que sim, mas foi em outra PR. Vou deixar para  mudar na outra pr, ok? essa aqui já está saturada haha

2021-10-29 20:04 UTC, VanderSant commented on src/components/button.js
> +};
meu objetivo era mais reduzir os imports na página principal, mas acho justo isso tbm

2021-10-29 20:48 UTC, VanderSant commented on src/server_communication/constants_api.js
> +  console.log('Id não encontrado - GetConstantsId\n');
tava pensando em deixar isso em mais alto nppivel, mas os toasts quembram o galho mesmo

2021-10-29 21:05 UTC, GabrielKishida approved these changes
Caiu o 5 reais aqui no pix, aprovado

2021-10-29 21:09 UTC, guedeslucas1 approved these changes

2021-10-29 21:10 UTC, merged

2021-10-29 21:10 UTC, VanderSant commented
amém