✨header e footer
ThundeRatz/Monitracer pull request #9
Opened 2021-10-13 19:27 UTC by guedeslucas1

Aqui implementamos o cabeçalho, rodapé e melhoramos a splashScreen para ficar parecida com a projetada no figma:

![image](https://user-images.githubusercontent.com/49926722/137199880-efa76841-3f14-4e90-8466-e22a912046bc.png)

Qualquer sugestão relacionada a design é muito bem vinda :)

Com a adição do footer, fizemos uma mudança na hierarquia das páginas do aplicativo, já que todas as tabs do footer estão contidas dentro de uma página principal `AppPage`. Dessa forma temos:

1. SplashScreen
2. AppPage
    - HomePage (acessível clicando no logo no header, e destino inicial após SplashScreen)
    - BluetoothListPage (acessível clicando no símbolo de bluetooth no header)
    - ConstantsPage
    - ControlPage
    - EvaluationPage
    - HistoryPage

2021-10-13 19:32 UTC, VanderSant commented
Reza a lenda que tem um DinoTracer escondido ai já haha

2021-10-14 17:14 UTC, d-nery requested changes

2021-10-14 17:14 UTC, d-nery commented on src/AppPage.js
> +import { EvaluationPage } from './tabs/EvaluationPage';
Ei, tá inconsistente espaço vs não espaço (`{ item }` vs `{item}`), o prettier deveria pegar isso 🤔 

Eu sou do time com espaços, mas o importante é deixar consistente

2021-10-14 17:14 UTC, d-nery commented on src/AppPage.js
> +            tabBarActiveBackgroundColor: '#047FF0', //thunderazul sucesso
Todas essas constantes do figma deveriam estar num arquivo dedicado de estilo, aí nos lugares você só usaria tipo `style.Primary` e não precisaria dos comentários (tem um ThemeProvider no react tbm se n me engano, que se quiserem poderia usar, mas aí n sei como funciona)

2021-10-14 17:14 UTC, d-nery commented on src/AppPage.js
> +              flex : 200,  // ???
???

2021-10-14 17:14 UTC, d-nery commented on src/AppPage.js
> +            ),
Essa identação parece errada, todas as de baixo tbm

2021-10-14 17:14 UTC, d-nery commented on src/SplashScreen.js
> +              clearTimeout(navigationTimeOut);
Ei, você n pode simplesmente skipar uma splash screen hahahah

2021-10-14 17:14 UTC, d-nery commented on src/components/header.js
> +});
Tem uns arquivos sem linha final, acho que só esqueceram de rodar o prettier mesmo, recomendo ligar o Format on Save do code, ajuda bastante

2021-10-14 17:14 UTC, d-nery commented on src/tabs/ControlPage.js
> +import {GoToPage,GoToTab} from '../utils/nav';
Vcs trocaram todos os GoToPage por GoToTab? Se n tá mais usando no arquivo, pode remover

2021-10-14 17:14 UTC, d-nery commented on src/utils/nav.js
> +var nav;
:desperate_penguin:

2021-10-14 17:34 UTC, guedeslucas1 commented on src/AppPage.js
> +            tabBarActiveBackgroundColor: '#047FF0', //thunderazul sucesso
Isso esta sendo feito [nessa branch](https://github.com/ThundeRatz/Monitracer/tree/develop/src/components), aí talvez podemos esperar a PR dela para darmos pull pra essa. Seria útil inclusive pra padronizar a fonte das labels dos textos do footer.

2021-10-14 19:53 UTC, VanderSant commented on src/AppPage.js
> +import { EvaluationPage } from './tabs/EvaluationPage';
é, eu esqueci de passar o prettier hahah ops

2021-10-19 17:49 UTC, guedeslucas1 commented on src/AppPage.js
> +              flex : 200,  // ???
Então, pra ser honesto eu não tenho certeza do porque isso ta dando certo assim (e só assim). Os icones do header só ficam no espaçamento que a gente estava imaginando pra um valor muito grande de `flex`. Inclusive tenho um pouco de receio de isso não estar funcionando direito em outros dispositivos. Se alguém puder testar seria bacana

2021-10-19 17:58 UTC, d-nery commented on src/AppPage.js
> +              flex : 200,  // ???
Na verdade eu comentei o ??? pq tem um //??? hahaha 
Mas sim, esquisito o 200

2021-10-19 18:00 UTC, d-nery commented on src/components/header.js
> +        <Ionicons name={'bluetooth'} color={'white'} size={30} />
Pq entre chaves se é um valor direto? hehe

2021-10-24 16:56 UTC, DamaralHenrique submitted a review, later dismissed
Me parece tudo certinho! Consegui testar aqui localmente sem problemas!
PS: Adorei o DinoTracer, ele ficou mto bom kkkk

2021-10-27 03:45 UTC, GabrielKishida submitted a review, later dismissed
Acho que tá tudo certo, só algumas mudanças de estilo que eu sugeriria

2021-10-27 03:45 UTC, LauraKishida commented on src/AppPage.js
> +        tabBarInactiveTintColor: 'gray',
Importante lembrar de pegar isso daq dos objetos do stylesheets depois

2021-10-27 03:45 UTC, LauraKishida commented on src/AppPage.js
> +            iconName = 'cog';
Dá pra fazer um map bem legal com coisas desse tipo:
```
const iconMap = {
  ConstantsPage : "add-circle-outline",
  HistoryPage : "list",
  ControlPage : "game-controller",
  OutraPageEsqueciONome : "cog"
};
...
iconName = iconMap[route.name]
```
Eu acho que era algo desse estilo, não bem isso. Nem sei se isso é útil, é só uma estrutura que eu acho interessante.

2021-10-27 03:45 UTC, LauraKishida commented on src/SplashScreen.js
> +    <View style={styles.container}>
Ué, pq tirou o touchable?

2021-10-27 03:45 UTC, LauraKishida commented on src/components/BTList.js
> +    ></FlatList>
hue
```suggestion
    />
```

2021-10-27 03:45 UTC, LauraKishida commented on src/components/header.js
> +        onLongPress={() => GoToDinoTracer()}
👀

2021-10-27 03:45 UTC, LauraKishida commented on src/AppPage.js
> +      />
Uma outra forma de fazer construções assim repetidas é fazer um map(). Acho que nesse caso pode ser útil:

```javascript
 {array.map((element) => {
      return (
        <View key={element.key} style={{margin: 10}}>
          <Text>{element.title}</Text>
          <Text>{element.subtitle}</Text>
        </View>)}
```

Não literalmente isso kkkkk mas algo assim

2021-10-27 03:45 UTC, LauraKishida commented on src/tabs/BluetoothListPage.js
> +    BTConnection();
Então, eu ia fazer a recomendação de transformar esse BTConnection pra que exportasse um objeto ao invés de um vetor. O problema de exportar vetores é que você é obrigado a puxar todos os elementos do vetor. Se fosse um objeto, você poderia puxar somente os elementos que você vai utilizar:

```suggestion
  const {BTInit, BTRemove, EnableBT, DisableBT, BTLogin} =
    BTConnection();
```

Mas se for mudar isso tem que mudar no export também

2021-10-27 03:45 UTC, LauraKishida commented on src/utils/nav.js
> +var nav;
Assim, menes à parte, não tem como manter essa variável de algum jeito mais agradável?

2021-10-27 19:32 UTC, guedeslucas1 commented on src/SplashScreen.js
> +    <View style={styles.container}>
A gente tirou a função de pular a splash screen clicando na tela (sugestão do @d-nery). Ela ta bem rapidinha, eu pessoalmente acho que ta td bem.

2021-10-27 19:43 UTC, d-nery commented on src/SplashScreen.js
> +    <View style={styles.container}>
Só pra explicar, a SplashScreen foi feita pra dar tempo de as coisas carregarem no background, não faz sentido poder pular arbitrariamente. Inclusive o correto é ela só acabar quando as coisas tiverem carregado, mas como isso é chato de verificar, num app desse tamanho colocar um tempinho fixo é ok e mais que suficiente, mas ainda assim n faz sentido deixar pular

2021-10-27 19:47 UTC, d-nery commented on src/AppPage.js
> +            iconName = 'cog';
Inclusive bem mais fácil de manter assim, só lembrando que não tem um "else" quando se usa um mapa, então seria

```js
iconName = iconMap[route.name] ?? "cog";
```

Pra ele pegar o cog como default caso não encontre.

Se quiserem ir além, podem criar um IconManager, que é uma classe e faz toda essa lógica, incluindo valores default, e pode cuidar de ícones que não são de páginas também

2021-10-28 20:12 UTC, GabrielKishida approved these changes
Fino do fino

2021-10-28 20:12 UTC, LauraKishida commented on src/utils/nav.js
> +}
Só dá mais um enter por causa do símbolozinho do github

2021-10-28 20:12 UTC, LauraKishida commented on src/utils/nav.js
> +  }
Nice! Acho que fica bem mais agradável ter essa leitura.

2021-10-29 14:34 UTC, d-nery commented on src/utils/nav.js
> +}
Tem uns whitespaces em outros lugares, lembrem de rodar o formatadorrr

Liga o format on save do VS Code, confia

2021-10-29 21:34 UTC, merged